### ISSUE TITLE
Does this code need some special configuration for work well?

### ISSUE THREAD

**Issue by sunshine99520** [paulirish/covfefe-coverage#1]
Dear paulirish,
After I installed the necessary node modules for the project, I run it as the picture you showed in the Readme file. Then I got this trace. 

```
D:\work_daily\covfefe-coverage-master>node .

D:\work_daily\covfefe-coverage-master\coverage.js:16


  .then(async chrome => {

        ^^^^^
SyntaxError: missing ) after argument list

    at createScript (vm.js:56:10)

    at Object.runInThisContext (vm.js:97:10)

    at Module._compile (module.js:542:28)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:390:7)

    at startup (bootstrap_node.js:150:9)
```

Do you have any suggestions for me? Thanks very much~

**Comment by paulirish** [comment]
yes you'll need to use  node >= 7.10.
